dependencies:
- name: kube-lego
  version: 0.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: external-dns
  version: 0.4.9
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: heapster
  version: 0.2.7
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: kubernetes-dashboard
  version: 0.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: kube2iam
  version: 0.8.0
  repository: https://kubernetes-charts.storage.googleapis.com/

