# disable components that are not needed
enabled:
  kube-lego: true
  external-dns: true
  heapster: true
  kubernetes-dashboard: true
  kube2iam: true

kube-lego:
  config:
    # set your email
    LEGO_EMAIL: foo@example.com
    # Uncomment for prod
    # LEGO_URL: https://acme-v01.api.letsencrypt.org/directory

external-dns:
  image:
    tag: v0.4.5
  podAnnotations:
    "iam.amazonaws.com/role": AWS_IAM_ROLE_FOR_ROUTE_53

kube2iam:
  host:
    iptables: true
    interface: cni0
  rbac:
    create: true
  extraArgs:
    auto-discover-base-arn: true

