# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

defaultRules:
  create: true

userAlerts:
  create: false
  yaml: null
  # yaml: |
  #   groups:
  #   - name: my-rules
  #     rules:
  #     - alert: DummyAlert
  #       annotations:
  #         message: This is a DummyAlert meant to ensure that the entire alerting pipeline is functional.
  #       expr: vector(1)
  #       labels:
  #         severity: none
prometheusReplicaCount: 1
alertManagerReplicaCount: 3
prometheusVersion: v2.0.0
alertManagerVersion: v0.13.0
service:
  prometheusInternalPort: 9090
  alertManagerInternalPort: 9093
  # prometheusExternalUrl: https://monitoring.example.com/prometheus
  # alertManagerExternalUrl: https://monitoring.example.com/alertmanager
ingress:
  enabled: false
  # Used to create an Ingress record.
  monitoringHost: monitoring.example.com
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    # The secret will be automatically created by kube-lego
    - secretName: monitoring-tls-cert
      hosts:
        - monitoring.example.com
resources:
  requests:
   memory: 400Mi

