# Default values for kube-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  server:
    adminPassword: supersecret
    image: "grafana/grafana:4.6.3"
    ingress:
      enabled: false
  service:
    type: ClusterIP

prometheus:
  # userAlerts:
  #   create: true
  #   yaml: |
  #     groups:
  #     - name: my-rules
  #       rules:
  #       - alert: DummyAlert
  #         annotations:
  #           message: This is a DummyAlert meant to ensure that the entire alerting pipeline is functional.
  #         expr: vector(1)
  #         labels:
  #           severity: none
  ingress:
    enabled: false
    monitoringHost: monitoring.domain.com

nodeExporter:
  jobLabel: node-exporter

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$

kube-state-metrics:
  # this is the default in 0.11.0
  rbac:
    create: true

phase1: false
phase2: false
