apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam-createcni0
  namespace: kube-system
  labels:
    app: kube2iam-createcni0
spec:
  template:
    metadata:
      labels:
        app: kube2iam-createcni0
    spec:
      containers:
        - name: sleep-forever
          image: gcr.io/google_containers/pause:0.8.0
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 10Mi

