apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "prometheus-cloudwatch.fullname" . }}
  labels:
    app: {{ template "prometheus-cloudwatch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-cloudwatch.name" . }}
        release: {{ .Release.Name }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.IAMRole }}
    spec:
      volumes:
        - name: config-plain
          configMap:
            name: {{ .Release.Name }}-config
            items:
              - key: data
                path: config.yml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: config-plain
              mountPath: /config
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
