apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "operator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "operator.fullname" . }}
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image={{ .Values.image.configReload.repository }}:{{ .Values.image.configReload.tag }}
        image: {{ .Values.image.operator.repository }}:{{ .Values.image.operator.tag }}
        name: {{ template "operator.name" . }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: http
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
