# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  operator:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.18.1
    pullPolicy: IfNotPresent
  configReload:
    repository: quay.io/coreos/configmap-reload
    tag: v0.0.1
    pullPolicy: IfNotPresent
service:
  internalPort: 8080
resources:
  limits:
   cpu: 200m
   memory: 100Mi
  requests:
   cpu: 100m
   memory: 50Mi

